### ISSUE TITLE
Dealing with -gnatg switch

### ISSUE THREAD

**Issue by Fabien-Chouteau** [jgrivera67/portable_minimal_ada_rts#1]
Hi German,

You are using the `-gnatg` switch here:
https://github.com/jgrivera67/portable_minimal_ada_rts/blob/a66019438515d482f8d12d6c9fe4003fe8f4327f/portable_minimal_ada_rts.gpr#L30

That's good because this switch is required to build a run-time project, however `-gnatg` also enables other switches ([see here](https://docs.adacore.com/gnat_ugn-docs/html/gnat_ugn/gnat_ugn/building_executable_programs_with_gnat.html)), in particular style checks that revert what you have set in `ADAFLAGS`. That's why you have build errors on Windows with the line termination warning. So you have to set `-gnatg` before the `ADAFLAGS` switches.

**Comment by jgrivera67** [comment]
Hi Fabien, thanks for catching this. Fixed.
